### ISSUE TITLE
Is this package still needed?

### ISSUE THREAD

**Issue by nomeata** [feuerbach/temporary#1]
`diff -Nur  temporary-1.2.0.3/ temporary-rc-1.2.0.3/` shows now differences besides the `.cabal` file. Is this package still necessary?

**Comment by UnkindPartition** [comment]
Has temporary got a reliable maintainer yet? If not, then this package is still needed.

**Comment by Fuuzetsu** [comment]
@feuerbach Did you consider taking over `temporary`? Since you created `temporary-rc`, there have been procedures put in place to allow this.

**Comment by Fuuzetsu** [comment]
@feuerbach I can also take over `temporary` if you don't want to maintain it yourself. Ideally we can phase `temporary-rc` out of use.

**Comment by UnkindPartition** [comment]
@Fuuzetsu I'm all for a new maintainer for temporary. It could be you, me, or, even better, both of us.

I hate going through the take-over procedure, but if you're willing to go through it, please do.

**Comment by Fuuzetsu** [comment]
https://mail.haskell.org/pipermail/libraries/2015-July/025990.html

**Comment by mboes** [comment]
cc @batterseapower

**Comment by Fuuzetsu** [comment]
@feuerbach I'm now `temporary` maintainer and I added you as second/backup maintainer. With this we should be able to abandon `temporary-rc`, correct? Notably in `tasty`.

**Comment by UnkindPartition** [comment]
I've switched tasty-golden and fsnotify to temporary, and marked temporary-rc as deprecated on hackage.

**Comment by nomeata** [comment]
Thanks!
