### ISSUE TITLE
Random number is not really random in template

### ISSUE THREAD

**Issue by robinp** [feuerbach/temporary#7]
`withTempDirectory` calls `createTempDirectory`, which seems to use PID. This is at least surprising, and in case of concurrent creations can be buggy?

**Comment by UnkindPartition** [comment]
I don't see why it is surprising or buggy — could you elaborate?

**Comment by robinp** [comment]
Maybe I misunderstand, but I would have expected each invocation to create a new unique temp dir. Instead, subsequent invocations in the same process yield the same temp directory (~template.pid).

For non-concurrent access, this is a mild inconvenience for example when debugging - it's hard to distinguish parts of the sequence based on the random dirname, say.

For concurrent access, concurrent parts of the program wolud get the same tempdir (note: I didn't try), so could overwrite each other's files or affect each other in some ways (like the first to finish would remove the tempdir).

**Comment by UnkindPartition** [comment]
It starts with the pid but then increments the number if the directory already exists.

```
System.IO.Temp> createTempDirectory "/tmp" "dir"
"/tmp/dir28217"
System.IO.Temp> createTempDirectory "/tmp" "dir"
"/tmp/dir28218"
System.IO.Temp> createTempDirectory "/tmp" "dir"
"/tmp/dir28219"
```

Does that address your concern?

**Comment by robinp** [comment]
Can live with it, thank you. A sentence in the Haddock would be nice about it, to avoid surprise.

**Comment by UnkindPartition** [comment]
What exactly do you find surprising about this?

**Comment by robinp** [comment]
Mislead by the Hackage page of temporary:


withTempFile ... String ... File name template. **See openTempFile**.

Re-exports from System.IO
openTempFile .... String ... File name template. If the template is "foo.ext" then the created file will be "fooXXX.ext" where XXX is some **random** number.

**Comment by UnkindPartition** [comment]
Ok, sorry you got misled, I'll document that. But let me point out that:

1. those are different functions, and they produce different results.

    ```
    System.IO.Temp> openNewBinaryFile "/tmp" "file.c"
    ("/tmp/file16816927771714636915.c",{handle: /tmp/file16816927771714636915.c})
    ```

    I suppose you may find the number 16816927771714636915 more "random".

2. even the number used by `createTempDirectory` is still random, as you don't know it ahead of time. There's no promise of any particular random distribution or independence of the PID.

**Comment by robinp** [comment]
Agree with (1). For (2) I would argue that for "random" people would at least expect "not predictable" or "different enough". Having the same number, or having an increasing number sequence falls far from that expectation.

Now I don't say you should change the implementation - If the behavior is documented that it is at least not surprising, should be fine. Thank you!
